# Example  .gitlab-ci.yml file
stages:
  - maventry
  - maventest
  - androidtry
  - androidtest

maven-build:   #this is a JOB
  stage: maventry
  tags:
    - springboot_tag  # this is LINK to the shell runner on the remote-server 
  script:
    - cd demo2
    - mvn package

maven-test:
  stage: maventest
  tags:
    - springboot_tag
  script:
    - cd demo2
    - mvn test
  artifacts:
    paths:
      - demo2/target/*.jar

    
android-build: #this is another job
  image: gjandres/android-ci:latest      # this is a directive to DOCKER
  stage: androidtry
  tags:
   - android_tag         #this is LINK to the docker runner on the remote-server        
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./frontend/semedicure/gradlew
  script:
    - cd frontend/semedicure
    - ./gradlew assemble

android-test:
  image: gjandres/android-ci:latest
  stage: androidtest
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./frontend/semedicure/gradlew
  tags:
   - android_tag
  script:
    - cd frontend/semedicure
    - ./gradlew test

